//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PR
    {
        public PR()
        {
            this.SD = new HashSet<SD>();
        }
    
        [Range(1001,2000,ErrorMessage="Неверный диапазон номера")]
        public int SNUM { get; set; }
        public string SNAME { get; set; }
        public string CITY { get; set; }
        public float COMM { get; set; }
    
        public virtual ICollection<SD> SD { get; set; }
    }
}
