//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD
    {
        public int ONUM { get; set; }
        public float AMT { get; set; }
        public System.DateTime ODATE { get; set; }
        public int CNUM { get; set; }
        public int SNUM { get; set; }
    
        public virtual PR PR { get; set; }
        public virtual ZK ZK { get; set; }
    }
}
