//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZK
    {
        public ZK()
        {
            this.SD = new HashSet<SD>();
        }
    
        public int CNUM { get; set; }
        public string CNAME { get; set; }
        public string CITY { get; set; }
        public int RATING { get; set; }
        public int SNUM { get; set; }
    
        public virtual ICollection<SD> SD { get; set; }
    }
}
